# Generated by Django 3.0.2 on 2020-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_puzzlepiece_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentsolution',
            name='verified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='crossed confidence threshold time'),
        ),
        migrations.AlterField(
            model_name='confidentsolution',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last modified date'),
        ),
    ]
