# Generated by Django 3.0.2 on 2020-01-19 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_puzzlepiece_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentsolution',
            name='verified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='crossed confidence threshold time'),
            preserve_default=False,
        ),
    ]
