---
- hosts: all
  become: true

  tasks:
    - name: decomission services
      docker_compose:
        project_src: "/puzzlepieces"
        state: absent
        remove_orphans: yes
        remove_volumes: yes
        remove_images: local
        pull: yes
      environment:
        URL: "{{ compose_env.URL }}"
        TLS_EMAIL: "{{ compose_env.TLS_EMAIL }}"
        IMAGE_TAG: "{{ compose_env.IMAGE_TAG }}"
        IS_DEBUG: "{{ compose_env.IS_DEBUG }}"
        DJANGO_SECRET_KEY: "{{ compose_env.DJANGO_SECRET_KEY }}"
        SQL_USER: "{{ compose_env.SQL_USER }}"
        SQL_PASSWORD: "{{ compose_env.SQL_PASSWORD }}"
        SQL_PORT: "{{ compose_env.SQL_PORT }}"
        SQL_PASSWORD_ROOT: "{{ compose_env.SQL_PASSWORD_ROOT }}"
        TRAEFIK_USER: "{{ compose_env.TRAEFIK_USER }}"
        TRAEFIK_PASS: "{{ compose_env.TRAEFIK_PASS }}"

    - name: remove application directory
      file:
        path: /puzzlepieces
        state: absent
        mode: "0755"
