---
- hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/{{ varsfile }}"
  environment:
    URL: "{{ URL }}"
    TLS_EMAIL: "{{ TLS_EMAIL }}"
    IMAGE_TAG: "{{ IMAGE_TAG }}"
    IS_DEBUG: "{{ IS_DEBUG }}"
    DJANGO_SECRET_KEY: "{{ DJANGO_SECRET_KEY }}"
    SQL_USER: "{{ SQL_USER }}"
    SQL_PASSWORD: "{{ SQL_PASSWORD }}"
    SQL_PORT: "{{ SQL_PORT }}"
    SQL_PASSWORD_ROOT: "{{ SQL_PASSWORD_ROOT }}"
    TRAEFIK_AUTHSTRING: "{{ TRAEFIK_AUTHSTRING }}"

  tasks:
    - name: create application directory
      file:
        path: /puzzlepieces
        state: directory
        mode: "0755"

    - name: verify composefile
      file:
        path: "/puzzlepieces/docker-compose.yml"
        state: present
        validate: "docker-compose -f %s config "

    - name: take services down
      docker_compose:
        project_src: "/puzzlepieces"
        state: absent
